# 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。
計算過程もマークダウンテキストを用いて説明してください。  
A = [[-1 2 3],[4 -5 6],[7,8,-9]]  
B = [[0 2 1],[0 2 -8],[2 9 -1]]

AB =  [  
[-1×0+2×0+3×2, -1×2+2×2+3×9, -1×1+2×(-8)+3×(-1)]  
[4×0-5×0+6×2, 4×2-5×2+6×9, 4×1-5×(-8)+6×(-1)]  
[7×0+8×0-9×2, 7×2+8×2-9×9, 7×1+8×(-8)-9×(-1)]  
= [  
[6, 29, -20],  
[12, 52, 38],  
[-18,-51-48],  
]

# 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。

In [92]:
import numpy as np
A = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
B = np.array([[0,2,1],[0,2,-8],[2,9,-1]])
print("A*B=\n{}".format(np.matmul(A,B)))

A*B=
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1.行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる   
2.行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる  
3.行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる  
4.それらの値を全て足し合わせる    
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [95]:
A[0,0]*B[0,0]+A[0,1]*B[1,0]+A[0,2]*B[2,0]

6

# 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。  
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

In [126]:
import numpy as np
import sys

#n×m行列の積を求める関数
def queue_mul(a,b):
    #ndarrayの準備
    a,b = np.array(a),np.array(b)
    
    #２次元配列の判定
    if a.ndim == 2 and b.ndim == 2:
        #a_index=aの行数,　　b_index=bの列数
        a_index,b_columns = len(a[:,0]),len(b[0,:])
        #returnするndarrayの初期化
        c = np.arange(a_index*b_columns).reshape([a_index,b_columns])
        
        #積の計算部分
        for i in range(a_index):
            for j in range(b_columns):
                #行列aのi行目と行列bのj列目を取り出して計算
                c[i,j] = np.sum(a[i,:]*b[:,j])
        return c
    #行列a,bが２次元ではないとき
    else:
        sys.exit("2次元の配列を入力してください")
    
x = queue_mul(A,B)
print(x)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。  
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [129]:
def queue_mul2(a,b):
    if len(a[0,:])==len(b[:,0]):
        return queue_mul(a,b)
    else:
        print("入力に誤りがあるため計算不可です")
        return None

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

#計算不可の行列を与える
print("計算結果:\n{}\n".format(queue_mul2(d_ndarray,e_ndarray)))

#計算可能な行列を与える
print("計算結果:\n{}".format(queue_mul2(A,B)))

入力に誤りがあるため計算不可です
計算結果:
None

計算結果:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [130]:
print("Dの転置行列とEの積:\n{}".format(queue_mul2(d_ndarray.T,e_ndarray)))

print("検算:\n{}".format(d_ndarray.T@e_ndarray))

Dの転置行列とEの積:
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
検算:
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
